name: TradingView Another Screenshot Bot

on:
  workflow_dispatch: # Manual run button
  schedule:
    - cron: '30 13 * * *'   # 7:00 PM IST (13:30 UTC)

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install Chrome and Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          pip install pandas selenium webdriver-manager gspread mysql-connector-python

      - name: Run Script
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: 3306
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          TRADINGVIEW_COOKIES: ${{ secrets.TRADINGVIEW_COOKIES }}
          GSPREAD_CREDENTIALS: ${{ secrets.GSPREAD_CREDENTIALS }}
        run: python another-screen.py
